# Generated by Django 3.1.7 on 2021-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255, unique=True)),
                ('overView', models.TextField(max_length=255)),
                ('year', models.DateField()),
                ('image', models.ImageField(upload_to='movie/image/% Y/% m/% d/')),
                ('video', models.FileField(upload_to='movie/video/% Y/% m/% d/')),
            ],
        ),
    ]
